version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "devDb"
    ports:
      - "5431:5432"
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file: "variables.env"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/devDb
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_JWT-SECRET=${JWT_AT_SECRET}
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - SPRING_SERVER="0.0.0.0"
      - SPRING_PORT="8080"
    ports:
      - 8080:8080
    depends_on:
      - postgres


