@startuml Startup Sequence

actor Actor
participant Frontend
participant Backend
participant "Notification Manager"
participant "Notification Sender"
database DB

Actor -> Frontend : open the app
activate Frontend

Frontend -> Backend : get User
activate Backend

Backend -> Frontend : User Object
deactivate Backend

Frontend -> Backend : subscribe for notifications
activate Backend

Backend -> "Notification Manager" : notify subscription
activate "Notification Manager"

"Notification Manager" -> DB : query all outstanding Notifications
activate DB
DB -> "Notification Manager" : list of all outstanding Notifications
deactivate DB

"Notification Manager" -> "Notification Sender" : send Notifications
deactivate "Notification Manager"
activate "Notification Sender"

Backend --> Frontend : subscribe confirmation
deactivate Backend

Frontend -> Backend : get current lobby
activate Backend
Backend -> Frontend : lobby
deactivate Backend

"Notification Sender" -> Frontend : List of Notifications (async)
deactivate "Notification Sender"

Frontend -> Actor : show stub Lobby
deactivate Frontend

@enduml