@startuml Startup Sequence

actor Actor
participant Frontend
participant Backend
database DB

Actor -> Frontend : open the app
activate Frontend

Frontend -> Backend : get User
activate Backend

Backend -> Frontend : User Object
deactivate Backend

Frontend -> Backend : subscribe for notifications
activate Backend

Backend --> Frontend : subscribe confirmation
deactivate Backend

Frontend -> Backend : get current lobby
activate Backend
Backend -> Frontend : lobby
deactivate Backend

Frontend -> Backend : get Invites
activate Backend
Backend -> Frontend : list of Invites
deactivate Backend

Frontend -> Actor : show Lobby
deactivate Frontend

@enduml