spring:
  application:
    name: Lets Play Backend
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  at-cookie-name: ${AT_COOKIE_NAME}
  rt-cookie-name: ${RT_COOKIE_NAME}
  jwt-secret: ${JWT_SECRET}
  at-expiration-in-ms: 900000
  rt-expiration-in-ms: 604800000

encryption:
  refresh-token-secret: ${RT_SECRET}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-login-endpoint: true