spring:
  application:
    name: Lets Play Backend
  datasource:
    url: jdbc:postgresql://localhost:5431/devDb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  at-cookie-name: access-token
  rt-cookie-name: refresh-token
  jwt-secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  at-expiration-in-ms: 900000
  rt-expiration-in-ms: 604800000

encryption:
  refresh-token-secret: kLh7Fgv5kLh7Fgv5kLh7Fgv5kLh7Fgv5

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-login-endpoint: true