spring:
  application:
    name: Lets Play Backend
  datasource:
    url: ENC(80BpL9v5qXLd07KA4zm0hkUSko8UgJE/B/6tqsJykoBH2J5llCFlRz3JW/sXJY0muM/zcV/QreZy6DhqEnzQvzncIw4VglZOsBVVqjXyoTQ=)
    username: admin
    password: ENC(7mAbYTzEhPHxqubHmLoCj+Bak7iLGIrZourE6a2X3JrlTb8XKmrp9H+As+qJr0FI)
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(D92W2tJto746zgVcgMhhcbiijC/sn7bY0/NjEsnJsLpsEDpNJHBRIdBcDdIzvPaIIlf150wTpS+gdex+MEXw0w==)
            client-secret: ENC(sg20KDL6xLsdvKUSkzcAjoHGPt0tJ/nslBYX289NHfc9cg/rzsZF18FKDYWoVi0Gzb55GEXJ+9z+g/4nYwUH5TlXXi20f4vtEY94KD1YjI8=)
            provider: github
            scope:
              - read:user
              - user:email
          discord:
            client-id: ENC(qe5HjX5b03OYej/kKALbYsFiw0F92vYZutnPefhi9cnXT+pJ8VjtZvGbvDOWUpfdNWvZm6TGkaSs+vuYzMJOIg==)
            client-secret: ENC(x6fgAq2mwyBSmTAlO9gIoh2zLy4YXMKdHWuzomLkHsn4a7Wdc6XkQHDpapXHY04/eypJvv19K98s7uYKCgkw8KbOcV5Q8PAu9TOGh5DU0JYLGy7vs2VyMNbyVodHmJCrkCSUcjh/WPsuP3jIgI9NBA==)
            redirect-uri: http://localhost:8080/login/oauth2/code/discord
            authorization-grant-type: authorization_code
            client-name: Discord
            provider: discord
            scope:
              - email
              - identify
              - openid
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          discord:
            authorization-uri: https:///discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: email

jwt:
  at-cookie-name: access-token
  rt-cookie-name: refresh-token
  jwt-secret: ENC(HB5zpIZmZLBFMdvVbRJFLTg2Qm115msh2QO+I7P9yNLwSUunA8zGYH2HbPBP5DMCikhprJech8IOUqgbGi0BdSdkKLYiHEOyoqeTk9y6/6OpPC8TwaCU6EJ9x8lsfEMy)
  at-expiration-in-ms: 900000
  rt-expiration-in-ms: 604800000
encryption:
  refresh-token-secret: ENC(7JNQ2ldqLJJo81CQR/2QM6GjHOo/c07UOjLGN/X8BdZyTE82I0dBWDqnOrxcPWo8BLVFgKpTUTT4Pp4UHrv2aJrskkSfoOzBu2Jdnd4YKZ8=)

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-login-endpoint: true
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        security: DEBUG
        http: DEBUG

