spring:
  application:
    name: Lets Play Backend
  datasource:
    url: ENC(fGuBWwB/Bln+P5puPViT004dwc0cRaeqDFzB+IPR0s7iVc2UuUi19StlhxQ5mPM9XGq628pFS95jGjV3PgfaR6XlVmyERlGUkvfCdg0j8/U=)
    username: admin
    password: ENC(7crvkvh5qUwXymmiKHm2BIsoaby8LbfPtHVIl24zfxpFW7SORr8dS3WQPXqc1fAQ)
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(DeZugMOQYn5FQ852tp4zuq+4gsdzEJwiEJikgcrupQ6KNHx3q9OtyWCU12SYdtyjlbY42PHu1c36MD5pNuwdtg==)
            client-secret: ENC(9l3XiWqWr65Wq28/FmvAdRHtJOEuuPTV3KbWHHL179CEHfK0GQsvDAeJ3YVK8hH/Q41teT/AMbx3h3xtV7K24cYDbiqa+jTTdoAL0bPYsO4=)
            provider: github
            scope:
              - read:user
              - user:email
          discord:
            client-id: ENC(9AXCDv4q/TdxXHILiigqjbyArtrYGatBHaGr0652RngtADYK6Wt+lkeqVWlMuy/PXMuRmZllQ7fXw50LzZaDdg==)
            client-secret: ENC(McbrnjuXQfxv43q3yN06h3l1tjyzJwJlp3RRBqa8NvTAvjvkfTgzagUPpR9BOpQ+vPj15kSBbU2tL8w8w2eVLxoax9E7mW66zCe2jGe3/fo=)
            redirect-uri: http://localhost:8080/login/oauth2/code/discord
            authorization-grant-type: authorization_code
            client-name: Discord
            provider: discord
            scope:
              - email
              - identify
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          discord:
            authorization-uri: https:///discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: id

jwt:
  at-cookie-name: access-token
  rt-cookie-name: refresh-token
  jwt-secret: ENC(rz0LCFlDXNQQxORJ31hoWrfzTSZq06Snk5CVtIXHdJvWEwx7vL/vJ37PDDWfYCkhZiM/klN3aQqW57MO193nI0HRzWiw/3+jTiRIWc+qpOWKFb2vs8eMY0gSHTKgzjqV)
  at-expiration-in-ms: 900000
  rt-expiration-in-ms: 604800000
encryption:
  refresh-token-secret: ENC(ifjWIJTtFuo27ZUsv1sRXcoZAWWgzTkDWQEJvaedqJcD/ama3bAwpj/vVHYejj/TpkvAbwAR0cCnjYQGElfgrI2haU/rd805BFb9iripCss=)

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-login-endpoint: true
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
#logging:
#  level:
#    org:
#      springframework:
#        transaction: DEBUG
#        security: DEBUG
#        http: DEBUG

