@startuml api

interface auth {
+ login()
+ logout()
}

interface User {
+ changeImg()
+ changeName()
+ changeAvailability()
}

class AppUser{
- long: id
- String: name
- String: email
- String: password
- String: avatarUrl
- List<UserRoles>: roles
- Lobby: currentLobby
}

enum UserRoleEnum{
ROLE_USER
ROLE_ADMIN
}

class AppUserRole{
- long: id
- UserRoleEnum role
}

AppUserRole -o UserRoleEnum
AppUser"*"--"*"AppUserRole

class Lobby{
- long: id
- String: title
- OffsetTime: time
- AppUser: owner
- List<Invite>: invites
}
AppUser "1"--> Lobby
Lobby "1"--> AppUser

@enduml